load/CompleteCheck.py
load/Config.py
load/InputFileset.py
load/PreValidate.py
py/dbt-etl.cfg

It has added the feature to read stocknumber.txt and call existing methods to verify that the stocknumbers provided in the text file are actually valid.
- With the next code we can read the content of stocknumber file.
```python
if filename == 'stocknumber.txt':
stocknumberData = s3Client.get_object(Bucket=bucket, Key=objKey)
contents = stocknumberData['Body'].read()
stocknumberArray = contents.decode("utf-8").splitlines()
```
- The next method is a new method to process the content of stocknumber file. 
```python
def validateUSXStockList(self, stockList, filenames, sampleText = None):
resultList = []
for stockListNumber in stockList:
result = self.validateUSXStockNo(stockListNumber, filenames, sampleText)
resultList.append(result)
return resultList
```
- python3 load/InputFileset.py test …

FCBHDBP-341 

---

load/InputFileset.py
load/PreValidate.py
load/PreValidateHandler.py

It has changed `PreValidate` class to create a constructor that accepts the bucket and an s3Client parameters.
The load/PreValidateHandler.py class was created inside the load folder because I couldn't run it from other folder. Also, I have added the config parameter because I couldn't connect to bucket without I use my credentials.
- `python3 load/PreValidate.py test Spanish_N2SPNTLA_USX`
- `python3 load/InputFileset.py test s3://etl-development-input Spanish_N2SPNTLA_USX`
- `python3 load/DBPLoadController.py test  s3://etl-development-input Spanish_N2SPNTLA_USX`
- `python3 load/PreValidateHandler.py test Spanish_N2SPNTLA_USX`

FCBHDBP-358 fix dbp-etl to work in lambda

---

load/FilenameParser.py
load/InputFileset.py
load/PreValidate.py

It has checked that the DBPLoadController works for the folder: "Kannada_N1 & O1 KANDPI_USX". It has added a validation to avoid that it handles the stocknumber.txt like a inputFileset.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-360
Run the next scripts:
```shel
python3 load/InputFileset.py test s3://etl-development-input "French_N2FRN PDC PDF PDV_USX"
python3 load/InputFileset.py test s3://etl-development-input "Kannada_N1 & O1 KANDPI_USX"
python3 load/InputFileset.py test s3://etl-development-input "French_N1 & O1 FRABIB_USX"
```

FCBHDBP-360 DBPLoadController - fix issue with Kannada

---

lambda/prevalidate/Handler.py
load/Handler.py
load/PreValidate.py
load/PreValidateHandlerStub.py

It has updated the method `validateLambda` to accept a new parameter which is the contents of the stocknumber.txt file. If it does not exist it will be an empty.
I have updated the load/PreValidateHandlerStub.py file to add the new parameter: stocknumbers
https://fullstacklabs.atlassian.net/browse/FCBHDBP-362
- You can test it if you run the next command
```shell
python3 load/PreValidateHandlerStub.py test "Kannada_N1 & O1 KANDPI_USX"
```
The above command is called without the new stocknumber parameter.
The output should be the next:
```shell
Copying lpts-dbp.xml...
LPTS Size. Prior: 4893, Current: 4893
LPTS Extract with 4893 records and 2763 BibleIds is loaded.
INFO: the following record has no stock number: EthName: Cebuano and AltName: Binisaya; Bisayan; …
```

FCBHDBP-362 etl-web frontend needs to pass contents of stocknumber.txt to Prevalidate lambda method

---

load/DBPLoadController.py
load/StageCLanguageReader.py
load/StageCLanguageRecord.py
load/StageCLanguageService.py
load/StageCLanguageServiceParse.py
load/TestLanguageReaderStage.py

It has created the new file: `TestLanguageReaderStage.py` to test the different method for the stage C. It has started to test the methods: `getBibleIdMap` and `getFilesetRecords10`.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-364
- You can test it if you run the next command:
```shell
python3 load/TestLanguageReaderStage.py test
```
Output
```shell
======================================================================
FAIL: test_get_bible_id_map_by_specific_bible (__main__.TestLanguageReaderStage)
----------------------------------------------------------------------
Traceback (most recent call last):
File "load/TestLanguageReaderStage.py", line 48, in test_get_bible_id_map_by_specific_bible
self.assertEqual(len(listStageC.get('SPAPDT')), len(listStageB.get('SPAPDT')), "Total …
```

FCBHDBP-364 ETL Stage C - implement StageCLanguageReader.getBibleIdMap

---

load/CompleteCheck.py
load/LPTSExtractReader.py
load/StageCLanguageReader.py
load/StageCLanguageRecord.py
load/StageCLanguageService.py
load/TestLanguageReaderStage.py

It has created the new file: `TestLanguageReaderStage.py` to test the different method for the stage C. It has started to test the methods: `getFilesetRecords`.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-364
- You can test it if you run the next command:
```shell
python3 load/TestLanguageReaderStage.py test
```
Output
```shell
======================================================================
FAIL: test_get_result_set_media (__main__.TestLanguageReaderStage)
----------------------------------------------------------------------
Traceback (most recent call last):
File "load/TestLanguageReaderStage.py", line 121, in test_get_result_set_media
self.assertEqual(stageCAllMediaRecordsLen, stageBAllMediaRecordsLen, "Total media records stage C [%s] and stage B [%s]" % …
```

FCBHDBP-366 ETL Stage C - implement getFilesetRecords

---

Dockerfile
docker/run.sh
lambda/generate-dbp-etl-cfg.sh
load/Config.py
load/FilenameParser.py
load/InputFileset.py
load/InputProcessor.py
load/S3Utility.py
load/UpdateDBPFilesetTables.py
load/UpdateDBPTextFilesets.py
load/Validate.py
py/dbt-etl.cfg

We need to add the following new record into `bible_fileset_types` to make sure that etl can insert the recrods:
| id | Description | name |
| --- | ----------- | ----------- |
| 19 | text_json | JSON Text Files |
This PR depends on the following sofria PR:
- https://github.com/faithcomesbyhearing/sofria-cli/pull/4
https://fullstacklabs.atlassian.net/browse/FCBHDBP-448
- You can run the next test unit and you should get the next output:
```shell
python3 load/DBPLoadController.py test s3://etl-development-input Spanish_N2SPNTLA_USX
```
- Output:
```shell
.
.
********** LPTS Tables Update ok **********
Completed:  SPNTLAN_ET-usx
Completed:  SPNTLAO_ET-usx
Completed:  SPNTLAN_ET
Completed:  SPNTLAN_ET-json
Completed:  SPNTLAO_ET
Completed:  SPNTLAO_ET-json
Num Errors  0
All Success in …
```

Fcbhdbp 448

---

load/UpdateDBPTextFilesets.py

It has increased the time out to 15 minutes to run sofria-client process.
I have tested it on my local environment using `Spanish_N2SPNTLA_USX` folder and it is taken around `3 minutes` to complete the entire process.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-448
- You can run the next test unit and you should get the next output:
```shell
python3 load/DBPLoadController.py test s3://etl-development-input Spanish_N2SPNTLA_USX
```
- Output:
```shell
.
.
********** LPTS Tables Update ok **********
Completed:  SPNTLAN_ET-usx
Completed:  SPNTLAO_ET-usx
Completed:  SPNTLAN_ET
Completed:  SPNTLAN_ET-json
Completed:  SPNTLAO_ET
Completed:  SPNTLAO_ET-json
Num Errors  0
All Success in RunStatus
```

FCBHDBP-448 Fix increase the time out to run sofria-client

---

load/InputFileset.py
load/UpdateDBPTextFilesets.py

It has changed the method: `getBiblePublisherVerses`. It has added a feature to removed some special char attached to verse number to make sure that verse will be of type number.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-455
Run the DBPLoadController using the following examples:
```shell
python3 load/DBPLoadController.py test s3://etl-development-input "Bakhtiari_P1BQIBMV_USX"
python3 load/DBPLoadController.py test s3://etl-development-input "Turkmen, Southern_P1TUKTTV_USX"
```

FCBHDBP-462 It has changed the method: getBiblePublisherVerses.

---

load/FilenameReducer.py
load/InputFileset.py
load/S3Utility.py
load/UpdateDBPTextFilesets.py
load/Validate.py

It has done a refactor to avoid to execute BiblePublisher command twice for a same fileset.
The following lines will invoke the method: validateFileset for a text_plain and this method will run BiblePublisher, if it doesn't return error, it will invoke the sofria cli. The above will void to execute BiblePublisher twice for a fileset of text type.
```python
errorTuple = texts.validateFileset("text_plain", inp.bibleId, inp.filesetId, inp.languageRecord, inp.index, filePath)
if errorTuple != None:
logger = Log.getLogger(inp.filesetId)
logger.messageTuple(errorTuple)
else:
derivativeFileset = texts.createTextFileset(inp)
results.append(derivativeFileset)
errorTuple = texts.invokeSofriaCli(filePath, inp.textFilesetId())
if errorTuple != None:
logger = Log.getLogger(inp.filesetId) …
```

FCBHDBP-463 Refactor to avoid to execute BiblePublisher twice

---

load/InputFileset.py
load/InputProcessor.py
load/LPTSExtractReader.py
load/PreValidate.py

It has updated the InputFileset class to change the filesetid when it is of type text and it formatted as a stocknumber. It will replace 2 peer '_'. E.g. fix to change the filesetid to be `ENGESVO_ET` when it is `ENGESVO2ET`.
We have done a similar logic that has been created into the `PreValidate` class, method: `validateFilesetId`. You can see it in the following line:
https://github.com/faithcomesbyhearing/dbp-etl/blob/master/load/PreValidate.py#L80
https://fullstacklabs.atlassian.net/browse/FCBHDBP-468
Run the DBPLoadController using the following examples:
```shell
python3 load/DBPLoadController.py test s3://etl-development-input "Spanish_N2SPNTLA_USX"
output:
BIBLE=ok, LPTS=ok, SPNTLAN_ET-usx=ok, SPNTLAO_ET-usx=ok, SPNTLAN_ET=ok, SPNTLAN_ET-json=ok, SPNTLAO_ET=ok, SPNTLAO_ET-json=ok …
```

FCBHDBP-468 UPLOADER (python) - bug loading text when directory name is filesetid

---

load/InputFileset.py
load/PreValidate.py
load/UpdateDBPTextFilesets.py

It has fixed an issue to avoid to run twice the text plain fileset and to avoid to overlook adding the usx fileset to the list.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-468
Run the DBPLoadController using the following examples:
```shell
python3 load/DBPLoadController.py test s3://etl-development-input "Spanish_N2SPNTLA_USX"
output:
BIBLE=ok, LPTS=ok, SPNTLAN_ET-usx=ok, SPNTLAO_ET-usx=ok, SPNTLAN_ET=ok, SPNTLAN_ET-json=ok, SPNTLAO_ET=ok, SPNTLAO_ET-json=ok
```
```shell
python3 load/DBPLoadController.py test s3://etl-development-input ENGWEBN2ET
output:
BIBLE=ok, LPTS=ok, ENGWEBN_ET=ok, ENGWEBN_ET-usx=ok, ENGWEBN_ET-json=ok
```
```shell
python3 load/DBPLoadController.py test s3://etl-development-input "Turkmen, Southern_P1TUKTTV_USX"
output:
BIBLE=ok, LPTS=ok, TUKTTVP_ET-usx=ok, …
```

FCBHDBP-468 Hotfix - UPLOADER (python) - bug loading text when directory name is filesetid

---

load/LPTSExtractReader.py
load/UpdateDBPLPTSTable.py
load/UpdateDBPLanguageTranslation.py

It has updated UpdateDBPLanguageTranslation to get the alternate name. But the altName is string with multple values that are delimited peer '|' and it must split the string into multiple altName records to create a insert statement for each altName.
We need to validate with Alan if the generated statement sqls  are correct. You can see the first version of the statement sql in the following URL: https://fullstacklabs.atlassian.net/browse/FCBHDBP-369?focusedCommentId=112606
https://fullstacklabs.atlassian.net/browse/FCBHDBP-369
- You can test it if you run the next command:
```shell
python3 load/UpdateDBPLanguageTranslation.py test
```

FCBHDBP-369 uploader (python) - Update language_translation table with alternate language name(s)

---

load/TextStockNumberProcessor.py

It has updated the Prevalidate validation to allow looking for stocknumbers with less than 8 characters.
I have updated the validation to allow looking for stocknumbers less than 7 characters. The above because I have saw that we have stocknumbers with length equals to 5 e.g. `C2WEB`, length = 6 e.g. `C2NIRV` and length = 7 e.g. `C2EKIDZ`
This PR depends on the following PR.
- https://github.com/faithcomesbyhearing/dbp-etl/pull/85
https://fullstacklabs.atlassian.net/browse/FCBHDBP-369?focusedCommentId=112653
```shell
python3 load/PreValidate.py test s3://etl-development-input "" English_C2WEB_USX B
python3 load/Validate.py test s3://etl-development-input English_C2WEB_USX
python3 load/DBPLoadController.py test s3://etl-development-input English_C2WEB_USX
```

FCBHDBP-469 UPLOADER (python) - recognize five character stocknumbers

---

load/LPTSExtractReader.py
load/LanguageReader.py
load/UpdateDBPLPTSTable.py

It has changed the logic to associate ND stocknumbers to ND Damids in UpdateDBPLPTSTable class. For now on, it will try to match the stocknumber to the filsetid by first checking if the filesetid belongs to a ND Stocknumber or a Reg Stocknumber.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-478
```shell
python3 load/UpdateDBPLPTSTable.py test
```
```shell
migration stage: [B]
LPTS Size. Prior: 5105, Current: 5105
LPTS Extract with 5105 records and 3030 BibleIds is loaded.
Database 'dbp_2022_03_18' is opened.
********* BEGIN LPTS UPDATE *********  2.3 sec
......
......
UPDATE bible_fileset_tags SET description='N1ZYP/WBT', admin_only='0', notes=NULL, iso='eng' WHERE hash_id='6daff755ae7d' AND name='stock_no' AND language_id='6414';
update bible_fileset_tags …
```

FCBHDBP-478 Uploader (python) Associate "ND" stocknumbers to "ND" Damids

---

load/InputFileset.py
load/LPTSExtractReader.py
load/LanguageReader.py
load/Validate.py

It has fixed an issue related to the text fileset TNKWBTN1ET. The issue was related because it is not transforming the filesetId to text filesetId when fileset contains number 1 rather 2. So, I have created a new method called `textLptsDamId` to transform the damId to text damId (e.g. `from TNKWBTN1ET to TNKWBTN_ET`) and the old method `textFilesetId` will transform the filesetId to a text textFilesetId (e.g.` from TNKWBTN1ET-json to TNKWBTN_ET-json`). 
Then, we have renamed to method: transformToTextFilesetId to transformToTextId because the above method should be used to transform the filesetId (e.g TNKWBTN1ET-json) or the damId (TNKWBTN1ET) and so, this method should be used for both case.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-486
@bradflood I have tested using the latest …

FCBHDBP-486 

---

load/LPTSExtractReader.py
load/UpdateDBPLanguageTranslation.py

It has updated the way to populate language_translations entity according LangName value. I have changed the way to loop through the languages records.
We were using `bibles = self.languageReader.getBibleIdMap()`  and for now on we are going to use `languageRecords = self.languageReader.resultSet` the above because we have some languages record that doesn't have a DBP_Equivalent value.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-491
- You should run the following command and you should get the inserts and update statements.
``shell
python3 load/UpdateDBPLanguageTranslation.py test
``
- Outcome
I have tested the current changes on my local environment and I got the following outcome.
[log_update_languages_translation.log](https://github.com/faithcomesbyhearing/dbp-etl/files/10078908/ …

FCBHDBP-491 updater (python) - populate based on LangName entry in lpts-dbp.xml

---

load/LPTSExtractReader.py
load/UpdateDBPLanguageTranslation.py

It has updated the class: `UpdateDBPLanguageTranslation` to add the feature to insert or update a language_translations record according to the EthName value. The priority for EthName record will be 5.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-496
- I have executed the following command on my local environment:
```shell
python3 load/UpdateDBPLanguageTranslation.py test
```
- and I got the following outcome:
[log_update_languages_translation_ethame.log](https://github.com/faithcomesbyhearing/dbp-etl/files/10117730/log_update_languages_translation_ethame.log)

FCBHDBP-496 updater (python) - upsert EthName into language_translation with priority = 5

---

load/FilenameParser.py
load/TextStockNumberProcessor.py
load/UpdateDBPLanguageTranslation.py
load/UpdateDBPTextFilesets.py
load/Validate.py

It has update `load/UpdateDBPLanguageTranslation.py` class be examining a running list of the keys to avoid to create insert/update sql strings for the same unique key.
Also, it has changed the way to invoke `sofria-client`, for now on, it will invoke the `sofria-client` before it creates JSON input fileset because the we need to create the JSON files before that it creates the  JSON input fileset.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-504
- I have executed the following command on my local environment to load "North Karelian_N1KRLIBT_USX":
```shell
python3 load/DBPLoadController.py test s3://etl-development-input "North Karelian_N1KRLIBT_USX"
```
The above command returned the following outcome:
[North Karelian_N1KRLIBT_USX.log](https://github.com/faithcomesbyhearing/dbp-etl/ …

FCBHDBP-504 Update UpdateDBPLanguageTranslation class to avoid create insert/update sql strings for the same unique key

---

load/UpdateDBPLPTSTable.py

It has updated load/UpdateDBPLPTSTable.py class to set `admin_only` to 1 for stock_no in `bible_fileset_tags`.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-504
- I have executed the following command on my local environment to update `bible_fileset_tags` entity:
```shell
python3 load/UpdateDBPLPTSTable.py test
```

FCBHDBP-500 Hotfix. uploader (python) - set admin_only to 1 for stock_no in bible_fileset_tag

---

load/FilenameParser.py
load/FilenameReducer.py
load/UpdateDBPFilesetTables.py
load/UpdateDBPLanguageTranslation.py
load/UpdateDBPTextFilesets.py
py/BibleFileTimestamps_Insert.py

The verse_start column has been changed from an integer type to a string type because sometimes a verse is represented as a string, such as '3a'. As a result, we have updated the verse_start column for the following entities: bible_verses, bible_files and bible_file_timestamps. Then, we have created a new column called verse_sequence of type integer for each above entity. As a result, we have replaced the column verse_start with verse_sequence in order to sort the records.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-515
- I have executed the following command on my local environment:
```shell
- python3 load/DBPLoadController.py test s3://etl-development-input BMUPNGN2ET
BIBLE=ok, LPTS=ok, BMUPNGP_ET-usx=ok, BMUPNGP_ET=ok, BMUPNGP_ET-json=ok
- python3 load/DBPLoadController.py test …
```

FCBHDBP-515 enable non-integer verse identifier

---

load/UpdateDBPFilesetTables.py
load/UpdateDBPTextFilesets.py

The type of the 'verse_end' column has been changed from string to integer, as we have decided to set this column equal to the 'verse_start' column.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-515
@bradflood The following are the statements sql to change the column:
```shell
-- bible_verses
ALTER TABLE bible_verses modify column verse_end char(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
-- bible_file_timestamps
ALTER TABLE bible_file_timestamps_temp modify column verse_end char(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL;
-- bible_files
ALTER TABLE bible_files modify column verse_end char(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL;
-- user_highlights
ALTER TABLE dbp_users.user_highlights modify column verse_end …
```

FCBHDBP-515 enable non-integer verse identifier - DBP-ETL

---

load/UpdateDBPFilesetTables.py

Modify the `insertBibleFiles` function to ensure that the keys related to 'bible_files' data are consistent during processing with those in the credits stream file. Additionally, implement a feature that updates the 'duration' column only if the compared values are different and the 'duration' value is not null or empty.
Dbp-etl was creating a INSERT statement because the keys are not matching due that the verseStart value fetched from etl was a integer (see convertChapterStart method invocation in this [line](https://github.com/faithcomesbyhearing/dbp-etl/blob/6636e04caead9cee845e5e771c8f6468303e4b47/load/UpdateDBPFilesetTables.py#L221)) and the verseStart value fetched from database was a string.
I have deactivated the invocation of method: `TranscodeVideo.transcodeVideoFileset` in …

FCBHDBP-555 uploader (python) - bible_file insert instead of update (keys don't match)

---

load/Config.py
load/UpdateDBPTextFilesets.py

Add a new option parameter to allow  to ignore any missing verses on the list. I have created a new data structure in the dbp-etl.cfg file to store the missing verses allowed. The structure looks like this:
```python
data.missing_verses_allowed = {
"BOOK_ID": { 
"CHAPTER_1" : [LIST_OF_VERSES],
"CHAPTER_2" : [LIST_OF_VERSES],
"CHAPTER_3" : [LIST_OF_VERSES] 
}
}
```
To illustrate how it works, I have included some sample data for the books of Luke, Mark, and John:
```python
data.missing_verses_allowed = {
"LUK": { "1" : [2, 5, 6], "3" : [6, 7, 8] },
"MRK": { "4" : [2, 5, 6] },
"JHN": { "11" : [9, 8, 1] },
}
```
The indexed array is sorted by book, chapter, and verses list. The purpose of this new data structure is to enable sofria_client to ignore any missing verses that are included in the …

FCBHDBP-556 uploader (python) for text: allow for missing verses

---

README.md
load/DBPLoadController.py
load/PreValidate.py
load/S3Utility.py
load/SQLBatchExec.py
load/UpdateDBPFilesetTables.py
load/UpdateDBPVideoTables.py

We haved divided the process of updating the video tables into two sub-processes. The first sub-process will update the bible_filesets and bible_files records. Then, the second sub-process will update the bible_file_stream_bandwidths and bible_file_stream_ts records. This second process will incorporate the changes made by the first sub-process and won't throw an SQL error because a foreign key has been removed. I'll share the log file with the outcomes of these two sub-processes.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-568
- I have executed the following command on my local environment:
```shell
python3 load/UpdateDBPVideoTables.py test s3://etl-development-input/ "ENGESVP2DV"
```
- Outcome
First sub-process to update the `bible_filesets` and `bible_files records` …

FCBHDBP 568 - uploader (python) - error uploading video which had already been loaded - KFFNRVP2DV

---

load/Config.py
load/DBPLoadController.py
load/TranscodeVideo.py
load/UpdateDBPVideoTables.py

The most recent modification involves dividing the process of updating Video Tables into two separate transactions. The first transaction updates the 'bible_filesets' and 'bible_files' records. Following this, the second transaction updates the 'bible_file_stream_bandwidths' and 'bible_file_stream_ts' records. However, I discovered an issue that necessitates closing the current database connection and initiating a new one after the first transaction. This ensures that any subsequent queries executed in the second transaction have access to the most recent changes pushed by the SQLBatchExec instance (dbOut). This is crucial as SQLBatchExec uses its own distinct database connection instance, separate from the 'self.db' instance used by the DBPLoadController class. See the following code …

FCBHDBP-582 continued work needed to fix duplicate key errors when loading video

---

load/AWSTranscoder.py
load/Config.py

Mocking Transcoder locally for audio. You can see the code in the following repository:
https://github.com/vichugofsl/dbp-etl-mock-transcoder
https://fullstacklabs.atlassian.net/browse/FCBHDBP-588
- I have executed the following command on my local environment:
```shell
python3 load/AWSTranscoder.py test s3://etl-development-input/ "JAAJARN2DA"
```
- Output
```shell
migration stage: [B]
LPTS Size. Prior: 5383, Current: 5383
LPTS Extract with 5383 records and 3105 BibleIds is loaded.
AWSSession. assume role arn: arn:aws:iam::869054869504:role/dbp-etl-dev
Created role arn:aws:iam::869054869504:role/dbp-etl-dev based session for s3.
No stocknumber.txt file found. bucket [etl-development-input], fullPath: [JAAJARN2DA], key [JAAJARN2DA/stocknumber.txt]
InputFileset …
```

FCBHDBP-588 Mocking Transcoder locally for audio.

---

Dockerfile

These changes were added to address an error in the docker build for dbp-etl-dev ([see build log](https://us-west-2.console.aws.amazon.com/codesuite/codebuild/078432969830/projects/dbp-etl-docker-dev/build/dbp-etl-docker-dev%3A7ac55fbd-e514-4966-abff-da9854a9cda4/?region=us-west-2))
See the Dockerfile for the explanation of the fixes (either an overriding env var, or using a virtual environment)
@vichugofsl - please review and fix if you know of a better way

fix externally managed environment error in docker build

---

load/UpdateDBPAccessTable.py

delete access id if not in LPTS and not 19x (offline permissions)
[User Story 2049](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2049): uploader: delete access groups if not in LPTS and not in 19x
Run the following command
```shell
python3 load/UpdateDBPAccessTable.py test
```
I have tested it in my local environment and you can see that the offline permissions are not being removed as you can see in the following file:
[Trans-test-lpts_sql.txt](https://github.com/faithcomesbyhearing/dbp-etl/files/14726279/Trans-test-lpts_sql.txt)

Task-2049 uploader: delete access groups if not in LPTS and not in 19x

---

load/UpdateDBPAccessTable.py

For certain bible texts, there is a bug regarding the set type code (Azure Devops 2137). This is causing thrashing (delete a row in one load, insert it in the next) that is noisy when evaluating the lpts upload during the blimp transition.
The affected hash_ids are associated with content not yet loaded, so this change will not provide unauthorized access to content.
This ticket will remove the logic to delete from 101 / 102 during the transition.

Don't delete access_groups 101 and 102 during Blimp transition

---

load/LoadOrganizations.py

Include `SQLBatchExec` in the `LoadOrganizations.py` class to avoid that it throws error when `load/DBPLoadController.py` invokes the  method `LoadOrganizations.update_database`. Additionally, added extra quotes to the licensor name in the insert statements. This change will prevent SQL statement failures during execution.
For example we need to add extra quotes to get the following insert:
```sql
INSERT IGNORE INTO organization_translations (organization_id, name, description, language_id) VALUES (@God_s_Word_to_the_Nations_Mission_Society__Inc_, 'God\'s Word to the Nations Mission Society, Inc.', 'God\'s Word to the Nations Mission Society, Inc.', '6414');
```
[User Story 2172](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2172): associate license orgs …

Task-2172 associate license org

---

load/SQLBatchExec.py
load/UpdateDBPAccessTable.py
load/UpdateDBPBiblesTable.py
load/UpdateDBPLPTSTable.py
load/UpdateDBPVideoTables.py

The primary capability being added is to correctly interpret the LPTS extract data so that licensors are associated correctly. This will handle agreement types of "Text Agreement" and "LORA", as well as Recording Status "Text Only". 
This PR also adds a capability to the language mapper, so that it now attempts to link languages between LPTS and Biblebrain using iso code, FCBH Language Name, and Country. Previously, we only considered iso code and FCBH Language Name

develop to master: Correct Licensor assignments

---

load/LoadOrganizations.py

Added logic to handle the audio fileset within the Other `Agreement/Render` option. Also, removed the log from the `Other/TraditionalRecording` option when the fileset is not audio, as it is being handled by the video process method.
[User Story 2176](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2176): Uploader: associate license orgs for  "Other"
[User Story 2179](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2179): associate org licenses for video (via copyright statement)
- You run the following command you will have a similar outcome.
```shell
python3 load/LoadOrganizations.py test 
```
- Outcome
[log_update_bibles_table.txt](https://github.com/faithcomesbyhearing/dbp-etl/files/15326784/log_update_bibles_table.txt)
I …

Task-2176 Uploader: associate license orgs for  "Other"

---

load/LoadOrganizations.py
load/UpdateDBPLPTSTable.py

It has added logic to set archived flag for a specific fileset when recording status in Discontinued, Inactive or Void. Improved logic to remove duplicate fileset records when ETL executes the UpdateDBPLPTSTable process.
[User Story 2183](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2183): uploader - set archived flag when recording status in Discontinued / Inactive / Void
You should run the following command and the outcome should be the following:
```shell
python3 load/LoadOrganizations.py test
```
- Outcome
[Trans-test-lpts.sql.txt](https://github.com/faithcomesbyhearing/dbp-etl/files/15370268/Trans-test-lpts.sql.txt)

Task 2183 uploader - set archived flag when recording status in Discontinued / Inactive / Void

---

load/UpdateDBPFilesetTables.py
load/UpdateDBPLPTSTable.py

Fixed an issue that was preventing the SQL statement from being built to update a bible_fileset record. It was not using the correct attrNames to build the SQL statament.
[Bug 2190](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2190): uploader text processing  - SQLExec error
I have executed the following command I did not get error:
```shell
python3  load/UpdateDBPFilesetTables.py test s3://etl-development-input Spanish_N2SPNTLA_USX
```

Task-2190 

---

Dockerfile

It is possible that the issue is related to apk, the package manager for Alpine Linux, which couldn't find the aws-cli package in its repositories. Therefore, aws-cli will be installed using Python pip instead of apk.
- I created the Docker image locally using the following command:
```shell
docker build . -t dbp-etl
```
- Then, I checked if the Docker image has correctly installed the AWS CLI using the following command and validated the outcome:
```shell
docker run --rm dbp-etl aws --version
```
- Outcome:
```shell
aws-cli/1.32.111 Python/3.12.3 Linux/6.8.0-76060800daily20240311-generic botocore/1.34.111
```

Task-2190 error with aws-cli installation

---

load/UpdateDBPVideoTables.py

Fixed the logic for inserting bible_file_stream_ts records, the fix was related to correctly using the method to sanitize SQL variable names.
This issue was introduced after the following PR which was merged on May 13:
https://github.com/faithcomesbyhearing/dbp-etl/pull/134
The above code created the method `sanitize_value` to sanitize SQL variable names but I didn't extend this method to the logic to update the video timestamps.
[Bug 2222](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2222): Uploader: video timestamps are not inserted correctly
- You should run the following command:
```shell
python3 load/UpdateDBPVideoTables.py test s3://etl-development-input/ "ENGESVP2DV"
```
- Outcome:
[Trans-test-video-ENGESVP2DV_sql.txt](https://github.com/user-attach …

Task-2222 Uploader: video timestamps are not inserted correctly

---

lambda/prevalidate/Handler.py
load/BlimpLanguageReader.py
load/BlimpLanguageRecord.py
load/BlimpLanguageService.py
load/BlimpLanguageServiceParse.py
load/DBPLoadController.py
load/InputFileset.py
load/InputProcessor.py
load/LanguageReader.py
load/LanguageReaderCreator.py
load/Log.py
load/PreValidate.py
load/PreValidateLambdaHandlerStub.py
load/S3Utility.py
load/TextStockNumberProcessor.py
load/UpdateDBPTextFilesets.py
load/Validate.py

Support Blimp as the system of record for BibleBrain data by setting the environment variable DATA_MODEL_MIGRATION_STAGE to BLIMP. Ensured the code works before Blimp becomes the system of record.
- Created a new [load/BlimpLanguageReader.py](https://github.com/faithcomesbyhearing/dbp-etl/compare/blimp...task-2101-support-blimp-system-record?expand=1#diff-95ea1b21a4bf737e4e1d09e2a50cb69a1b5065a90b56f721a2e79135e2077e05)
- Removed all Orthography constraints
- Load content proces will always point to BLIMP stage because the lpts.xml should be used
- Add constraint in [load/Validate.py](https://github.com/faithcomesbyhearing/dbp-etl/compare/blimp...task-2101-support-blimp-system-record?expand=1#diff-d1a2030b8c842850da3772bec71bf13fb640ca3b151227b1350f282ae29f7003) to check if the …

Task-2101 support Blimp as system of record; activate via environment variable

---

load/S3Utility.py
load/UpdateDBPLicensorTables.py

1. Removed incorrect logic that was preventing the upload of primary and derived filesets.
2. Additionally, I removed unnecessary logic that attempted to update the copyright information of an existing derived fileset using the same information.
[Bug 2371](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2371): uploader (text): usx and json not being uploaded
You can run the following command and the outcome should be the following:
`````shell
python3 load/DBPLoadController.py test s3://dbp-etl-upload-dev-ya1mbvdty8tlq15r/ "2024-11-26-14-27-01/Semai_N2 & P2 SEAWYI_USX"
`````
[log_upload_filesets.txt](https://github.com/user-attachments/files/17922269/log_upload_filesets.txt)

Task-2371 uploader (text): usx and json not being uploaded

---

load/DBPLoadController.py
load/UpdateDBPFilesetTables.py

Add logic to include the license group when a derived fileset is being uploaded.
[Bug 2382](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2382): uploader: when creating derived filesets, link to the license group of the primary
I have tested it using the following command:
````shell
````
- You can see in the last line that the license_group_filesets record is created.
[Trans-ENGESVN2DA-opus16.sql.txt](https://github.com/user-attachments/files/18161689/Trans-ENGESVN2DA-opus16.sql.txt)

Ticket-2382 when creating derived filesets, link to the license group of the primary

---

load/BlimpLanguageReader.py
load/BlimpLanguageService.py
load/Booknames.py
load/DBPLoadController.py
load/FilenameParser.py
load/PreValidate.py
load/TextStockNumberProcessor.py
load/UpdateDBPBooksTable.py

Added logic to support loading content based on filesets related to the Covenant Film.
[User Story 2021](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2021): uploader needs to recognize Covenant film content
- You can run the following command to test
````shell
time python3 load/DBPLoadController.py test s3://etl-development-input/ "Covenant_Manobo, Obo SD_S2OBO_COV"
````
You can see the sql outcome to create the entities: `bible_files` and `bible_books`: [Trans-OBOCOVS2DV.sql.txt](https://github.com/user-attachments/files/18236413/Trans-OBOCOVS2DV.sql.txt)
- You can run the following command to test UpdateDBPBooksTable:
````shell
time python3 load/UpdateDBPBooksTable.py test s3://etl-development-input/ "Covenant_Manobo, Obo SD_S2OBO_COV"
````
`````shell …
```

Task-2021 uploader needs to recognize Covenant film content

---

load/FilenameParser.py
load/TestFilenameParser.py

It updated the validation logic and modified the regex expression to use a stricter validation for ensuring that audio, text, and video files follow the correct pattern.
[User Story 2559](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2559): tighten the regex patterns for uploader filenames
- You can run the following functional test to ensure that the current changes do not break the validation process
`````shell
``````
@bradflood The FilenameParser process will not recognize the videos for fileset TGKWBTP2DV because it does not currently use the correct pattern.
- You can run the following unit test to validate the changes and the result should successful.
````shell
python3 load/TestFilenameParser.py test
````
````shell …

Ticket-2559 tighten the regex patterns for uploader filenames

---

load/FilenameParser.py
load/SQLBatchExec.py
load/UpdateDBPLPTSTable.py
load/Validate.py

Fixed the license_group_id references in the bible_filesets entity and Task-2628 reverted the change removing the regex used to parse the JSON file—since we still need to retrieve book and chapter information from it.
@bradflood According to Task-2628, I have reverted the regular expression used to parse JSON files because it is needed to extract book and chapter data from file. However, I removed the other text extensions in Validate.py, allowing us to load only USX file types for text filesets while still parsing the derived JSON files.
[Bug 2627](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2627): uploader - incorrect table references
[Bug 2628](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2628): uploader: json files …

Task-2627 uploader - incorrect table references and  Task-2628 uploader json files not parsed correctly

---

load/FilenameParser.py

Fixed the parsing method to retrieve the bookId from the video3 pattern. The method setBookName is no longer necessary because we need to use the book id instead of book name
[Bug 2630](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2630): (hotfix) uploader video not finding MRK
- If you run the following command it should return a successful outcome:
`````shell
time python3 load/FilenameParser.py test s3://etl-development-input/ "URIWBTN2DV"
``````
````shell
Found 1 filesets to process
FilenameParser: video/URIWBT/URIWBTN2DV typeCode: video
FilenameReducer. Create file:  /home/vichugof/files/accepted/video_URIWBT_URIWBTN2DV.csv
Total Files: 36 -> video/URIWBT/URIWBTN2DV
Success Count: video3 -> 35
Success Count: video4 -> 1
````
- If you run the following …
```

Task-2630 (hotfix) uploader video not finding MRK

---

load/FilenameParser.py
load/TestFilenameParser.py

The regex for validating and parsing the video files has been updated.
[User Story 2559](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2559): (R)tighten the regex patterns for uploader filenames
You can run the unit test `load/TestFilenameParser.py` and you will view the following outcome for video:
````shell
=====================================
File Type :  video
=====================================
❌ Invalid: English_KJV_JHN_1-1-18.mp4 (No pattern matched)
✅ Valid: English-KJV_JHN_1-1-18.mp4 (Matched: video1)
- Group 1: English-KJV
- Group 2: JHN
- Group 3: 1
- Group 4: 1
- Group 5: 18
- Group 6: mp4
❌ Invalid: English_KJV_JHN_1-1-18.mp4 (No pattern matched)
✅ Valid: English_JHN_1-1-18.mp4 (Matched: video1)
- Group 1: English
- Group 2: JHN
- Group 3: …
```

Ticket-2559 (R)tighten the regex patterns for uploader filenames

---

load/SQLUtility.py
load/TestFilenameParser.py
load/UpdateDBPBooksTable.py

Add a feature to prevent overwriting Bible book names when a localized book name is available for the video loading process.
[Bug 2629](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2629): uploader - loading video causes bible_books localized names to be overwritten with English
I have used the following two examples and I saw that won't try to overwrite the bible book names:
````shell
-> python3 load/UpdateDBPBooksTable.py test s3://etl-development-input/ "Covenant_Aceh SD_S2ACE_COV"
*** DBPLoadController:validate ***
Database 'dbp_2025_03_06' is opened.
Found 1 filesets to process
FilenameParser: video/ACECOV/ACECOVS2DV typeCode: video
FilenameReducer. Create file:  /home/vichugof/files/accepted/video_ACECOV_ACECOVS2DV.csv
DBPLoadController:validate. …
```

Task-2629 uploader - loading video causes bible_books localized names to be overwritten with English

---

load/S3ZipperService.py
load/UpdateDBPBibleFilesSecondary.py

Improved version of S3ZipperService class with an added feature to dynamically generate a custom file mapper JSON. This new functionality extracts the directory from the first file in the file_paths list, builds a JSON object in the expected format, uploads it to the same S3 folder as the zip output and then uses that file’s S3 key as the fileMapper value. Once the zip process completes, the file mapper is removed from S3.
I have used the fileset: SPNBDAP2DV as example and I executed the following command:
````shell
time python3 load/DBPLoadController.py test s3://etl-development-input/ "SPNBDAP2DV"
````
It will create a zip file named SPNBDAP2DV_MRK, and the path structure should match what’s shown in the following screenshot.

Task-2614 (R)uploader: create and publish zip for Gospel Films

---

load/BlimpLanguageRecord.py
load/DBPLoadController.py

Added logic to synchronize the Monday Product Code Board when an audio fileset is loaded.
[User Story 2631](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2631): uploader: update CPC after successful audio load
- You can try to load content for the fileset: ENGESVN2DA
`````shell
time python3 load/DBPLoadController.py test s3://etl-development-input/ "ENGESVN2DA"
`````
- Then, you should view the product code: N2ESV in the Monday CPC board.

Task-2631 uploader: update CPC after successful audio load

---

load/FilenameParser.py
load/FilenameReducer.py
load/UpdateDBPFilesetTables.py

Included logic to set a sequence for the end credit file in video filesets. Additionally, added logic to calculate the maximum chapter and verse for each book according to the files, which will later be used to set the verse start number (verse_sequence) for files that are “end” files of a book.
[Bug 2658](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2658): uploader for video does not set verse_sequence for end credits
I have used the following fileset: URIWBTN2DV
`````shell
python3  load/UpdateDBPFilesetTables.py test s3://etl-development-input URIWBTN2DV
`````
- Outcome
[Trans-test-URIWBTN2DV_sql.txt](https://github.com/user-attachments/files/19697085/Trans-test-URIWBTN2DV_sql.txt)

Task-2658 uploader for video does not set verse_sequence for end credits

---

load/InputFileset.py
load/S3Utility.py
load/UpdateDBPFilesetTables.py

Added logic to include all content related to video filesets, and fixed the logic (Task-2658) so that, for end‑of‑book video content, verse_end = verse_start and chapter_end = chapter_start
[User Story 2624](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2624): Video Uploader should create metadata for mp4 files
[Bug 2658](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2658): (R)uploader for video does not set verse_sequence for end credits
I have used tow filesets, video and audio: SPNBDAP2DV and ENGESVN2DA
- You can check that for the SPNBDAP2DV fileset all content will be created: _web.mp4, mp4 and m3u8
````shell
time python3 load/UpdateDBPFilesetTables.py test s3://etl-development-input SPNBDAP2DV
````
- Outcome …

Task‑2624 and 2658: Video Uploader should create metadata for mp4 files and uploader for video does not set verse_sequence for end credits

---

load/InputFileset.py
load/S3Utility.py
load/UpdateDBPBibleFilesSecondary.py
load/UpdateDBPFilesetTables.py

- Task-2692 – Fixed the logic for calculating the file size of Bible files attached to a video fileset. We now use the S3 client to obtain the file-size values for both .m3u8 and _web.mp4 files.
- Task-2697 – Improved the logic for creating records in bible_files_secondary for both audio and video filesets. The comparison constraint no longer includes the full path and video filesets are now covered by the insertion logic.
[Bug 2692](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2692): uploader filesize incorrect
[Bug 2697](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2697): uploader issues with zip file in bible_files_secondary
I have used the following two filesets:
``````shell
time python3 load/DBPLoadController.py test …

Task-2692: uploader filesize incorrect and uploader issues with zip file in bible_files_secondary

---

load/DBPLoadController.py

limit Monday Board updates to only the stocknumber and bible_brain_link attributes.
[User Story 2467](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2467): (R)Enable loading of Acts films
- I have used the fileset ID: FANBSGP2DV
````````````shell
time python3 load/DBPLoadController.py test s3://etl-development-input/ "FANBSGP2DV"
`````````````
Check in CPC Monday Board that the prodcut code has been updated.

Task-2467 Hotfix: (R)Enable loading of Acts films

---

load/SQLBatchExec.py
load/UpdateDBPFilesetTables.py

Updated the unique constraint on bible_files to include the file_name column. The filename will now be taken into account when generating the update statement.
[Bug 2714](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2714): uploader: update bible_files needs another constraint
I have used the following 3 filesets to test: SPNBDAP2DV (video), ENGESVN2DA (audio) and Spanish_N2SPNTLA_USX (text) and the command:
```````shell
-> python3 load/UpdateDBPFilesetTables.py test s3://etl-development-input SPNBDAP2DV
UPDATE bible_files SET file_name = 'Spanish-BDA_MAT_10-1-23_stream.m3u8' WHERE hash_id='b18563a987c4' AND book_id='MAT' AND chapter_start='10' AND verse_start='1' AND file_name='Spanish_BDA_MAT_10-1-23_stream.m3u8'; -- …

Task-2714 Updated the unique constraint on bible_files to include file_name.

---

load/S3ZipperService.py

fixed the s3zipper service so it no longer inserts a leading '/' when generating the mapper file. This prevents every file name from starting with '/'.
[Bug 2717](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2717): uploader zip: remove leading /
You can see the difference between two zip files before and after this change:
``````````shell
unzip -l SPNBDAP2DV_JHN.zip 
Archive:  SPNBDAP2DV_JHN.zip
Length      Date    Time    Name
---------  ---------- -----   ----
338  2025-04-25 15:12   /Spanish-BDA_JHN_10-1-21_web.mp4
350  2025-04-25 15:12   /Spanish-BDA_JHN_End_Credits_web.mp4
---------                     -------
688                     2 files
unzip -l SPNBDAP2DV_MRK.zip 
Archive:  SPNBDAP2DV_MRK.zip
Length      Date    Time    Name
--------- …
```

Task-2717 uploader zip: remove leading "/"

---

load/UpdateDBPFilesetTables.py

Fixed the logic for deleting a bible_files record for video filesets. The issue occurred because file_name was added to the unique constraint, but it was not included in the DELETE statement's condition.
[Bug 2714](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2714): (R)uploader: update bible_files needs another constraint
I have used the filset: SPNBDAP2DV
``````shell
time python3 load/UpdateDBPFilesetTables.py test s3://etl-development-input SPNBDAP2DV
DELETE FROM bible_files WHERE hash_id='b18563a987c4' AND book_id='MRK' AND chapter_start='10' AND verse_start='16' AND file_name='Spanish-BDA_MRK_10-16-21_web.mp4';
``````

Task-2714 (R)uploader: update bible_files needs another constraint

---

load/DBPLoadController.py
load/MondayHTTP.py
load/RunStatus.py
load/TestMondayHTTP.py

While investigating Task 2760, I reproduced the issue that occurs when for example the Monday API key in the cfg file is incorrect. A wrong key results in a 401 response, but the existing code handled it the same way as a network error or an empty response.
To address this, I improved the class: "load/MondayHTTP.py" so that Monday HTTP server errors (e.g. 401 responses) are reported in greater detail.
Added a new RunStatus component, UpdateMonday, for each fileset to indicate whether ETL succeeds or fails in updating Monday. Added logic to treat all 4xx and 5xx responses as retryable errors. Increased the retry delay to 1.5 seconds and applied exponential back-off.
Here’s an updated MondayHTTP.py with a proper exponential-backoff retry loop that:
- Retries on 429, 500, 502, 503, and 504
- …

Task-2760 uploader: update CPC failed

---

load/DBPLoadController.py
load/FilenameParser.py
load/FilenameReducer.py

Fix the loading process to prevent uploading content if the process fails (e.g., due to file parsing errors). Currently, it uploads the CSV file regardless of whether an error occurs.
[Bug 2712](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2712): uploader: for failed attempt, content is still being stored to S3
- You should run the following command and I have to get the following output:
```````shell
time python3 load/DBPLoadController.py test s3://dbp-etl-upload-newdata-fiu49s0cnup1yr0q/ "2025-04-28-20-53-43/YAOGOIP1DA"
```````
- You can see that it only uploaded the Errors.out file.
- Output
``````shell
*** DBPLoadController *** 
Config:setConfigParametersFromProfile. profile: test, programRunning: DBPLoadController.py …

Task-2712 uploader: for failed attempt, content is still being stored to S3

---

load/UpdateDBPBibleFilesSecondary.py

Fix the path used to push the PDF for video content. This update corrects the bucket name to use dbp-vid-ENVIRONMENT instead of dbp-ENVIRONMENT.
[User Story 2800](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2800): include copyright pdf in zip files created by uploader[User Story 2800](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2800): include copyright pdf in zip files created by uploader
I have used the following command to test it:
``````shell
time python3 load/DBPLoadController.py test s3://etl-development-input/ "FANBSGP2DV"
````````

Task-2800: Fix the path used to push the PDF for video content

---

load/UpdateDBPBibleFilesSecondary.py

Following the latest update to the Biblebrain-Services API, this PR changes the logic to generate the copyright PDF using the product code rather than the stock number.
[Bug 2844](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2844): Uploader: Use product code to generate the copyright PDF
I have tested using the following two command and I have validated that the zip file contains the copyright pdf:
- Audio Content
``````shell
time python3 load/DBPLoadController.py test s3://etl-development-input/ "ENGESVN2DA"
```````
- Video Content
``````shell
time python3 load/DBPLoadController.py test s3://etl-development-input/ "FANBSGP2DV"
```````

Task-2844 Uploader: Use product code to generate the copyright PDF

---

.gitignore
load/DBPLoadController.py
load/UpdateDBPFilesetTables.py
load/UpdateDBPLPTSTable.py

Update the logic to insert rows into the bible_files_secondary entity. The logic for updating the bible_files_secondary entity has been separated into a different method. It is now invoked after the product code has been inserted and the ZIP file has been generated.
[Bug 2844](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2844): Uploader: Use product code to generate the copyright PDF
You can check int the dev uploader environment the changes according to the test using BUNBSLN1DA
I have used the following command to test these changes:
`````````shell
time python3 load/DBPLoadController.py test s3://etl-development-input/ "BUNBSLN1DA"
`````````

Task-2844 The logic for updating the bible_files_secondary

---

load/UpdateDBPBibleFilesSecondary.py

Include the book in the copyright PDF when the fileset contains video content.
[User Story 2856](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2856): uploader (video): include book in copyright  pdf
```````shell
-> time python3 load/DBPLoadController.py test s3://etl-development-input/ "FANBSGP2DV"
Starting zip process with payload: bucket: dbp-vid-staging file_paths: ['dbp-vid-staging/video/FANBSG/FANBSGP2DV/copyright_ACT.pdf'] zip_output_prefix: video/FANBSG/FANBSGP2DV/FANBSGP2DV_ACT.zip fileMapper: dbp-vid-staging/video/FANBSG/FANBSGP2DV/fileMapper_20250714T181421.json
-> time python3 load/DBPLoadController.py test s3://etl-development-input/ "BUNBSLN1DA"
Starting zip process with payload: bucket: dbp-staging file_paths: …

Task-2856 uploader (video): include book in copyright  pdf
