load/CompleteCheck.py
- FCBHDBP-351 It has changed the query to fetch the books with placeholders.
- FCBHDBP-350 It has updated the logic to fetch filesets without access groups because they must have status equals to 'live'. To know if a fileset is 'live' it will look up the fileset in the LPTS extract (lpts-dbp.xml) using the LPTSExtractReader.
It has added the changes related to the ticket: FCBHDBP-350 as well. 
- https://fullstacklabs.atlassian.net/browse/FCBHDBP-351
- https://fullstacklabs.atlassian.net/browse/FCBHDBP-350
I have run the next script and I got the next output.
- python3 load/CompleteCheck.py test full
```shell
Created role arn:aws:iam::869054869504:role/dbp-etl-dev based session for s3.
ContinuationToken …
```
=> FCBHDBP-351 CompleteCheck - modify report "books with placeholders"

load/PreValidateHandlerStub.py
It has renamed the file: load/PreValidateHandler.py to load/PreValidateHandlerStup.py
https://fullstacklabs.atlassian.net/browse/FCBHDBP-358
=> FCBHDBP-358 fix dbp-etl to work in lambda

load/AWSSession.py, load/Config.py
revert earlier changes to align with automated build work in terraform and etl-web
=> automated build capability

load/InputFileset.py, load/LPTSExtractReader.py, load/PreValidate.py, load/UpdateDBPAccessTable.py
It has checked that the DBPLoadController works for the folder: "Kannada_N1 & O1 KANDPI_USX"
I have see 3 points:
1. I had an issue in the file PreValidate.py and the method: getStockNumbersFromFile. The issue was related to the stocknumber.txt files with line break in the end of file. The method is returning a empty stocknumber if the stocknumber.txt file had line break in the end of file. It has been fixed to support files with line break.
You can test it with if you run:
```shell
python3 load/InputFileset.py test s3://etl-development-input "Kannada_N1 & O1 KANDPI_USX"
```
you should see the message:
```shell
=======================================================
validateDBPELT stockNumbers =>  ['N1KAN/DPI', 'O1KAN/DPI']
=======================================================
```
2. …
=> FCBHDBP-360 DBPLoadController - fix issue with Kannada

lambda/prevalidate/Handler.py, load/AWSTranscoder.py, load/CompleteCheck.py, load/DBPLoadController.py, load/InputFileset.py, load/InputProcessor.py, load/LPTSExtractReader.py, load/LanguageReaderCreator.py, load/LoadOrganizations.py, load/PreValidate.py, load/PreValidateLambdaHandlerStub.py, load/S3Utility.py, load/TranscodeVideo.py, load/UnicodeScript.py, load/UpdateDBPAccessTable.py, load/UpdateDBPBibleFilesSecondary.py, load/UpdateDBPBibleTranslations.py, load/UpdateDBPBiblesTable.py, load/UpdateDBPBooksTable.py, load/UpdateDBPFilesetTables.py, load/UpdateDBPLPTSTable.py, load/UpdateDBPTextFilesets.py, load/UpdateDBPVideoTables.py, load/Validate.py
adjustments needed to work with Lambda
=> update LanguageReaderCreator interface 

load/Config.py, load/UpdateDBPLPTSTable.py, load/UpdateDBPLanguageTranslation.py
It has created a new class: load/UpdateDBPLanguageTranslation.py to update the records that belongs to the language_translation table according to the language name and heart name of languageReader records.
It has added the line to invoke the new class into [load/UpdateDBPLPTSTable.py](https://github.com/faithcomesbyhearing/dbp-etl/pull/46/files#diff-a8b84dcb2a008d41509d439d0dad3855517bc429e17563a012d78d868ced3024) line 48.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-374
- You can test it if you run the next command:
```shell
python3 load/UpdateDBPLanguageTranslation.py test
```
- Output
```shell
.
.
.
UPDATE language_translations SET name='Djime, Djiwe, Zime, Zime of Kélo', updated_at='2022-05-11 10:12:43.324176' WHERE language_source_id='4304' AND language_translation_id='6414' …
```
=> FCBHDBP-369 Update language_translation table with language name and heart name

.gitignore, load/Config.py, load/InputFileset.py, load/TestUpdateDBPBibleFileTags.py, load/UpdateDBPBibleFileTags.py
It has created a class to update ETL to populate table 'bible_file_tags' with Gospel Films thumbnails. We need to match book_id, chapter_start, verse_start between bible_file data in database and the S3 filename, which needs to be parsed to determine book/chapter/verse filenames from S3 will be of the form: `gf_luk_12_01.jpg`. So, in some cases, the chapter and verse won't match between the bible_file data and the filename then we need to find the closest verse.
According to above we created a method to index the thumbnails file list by book/chapter/verse. The method is named: `getThumbnailFilesDictIndexedBookChapterVerse`. And we have created a method to get the closest verse given a list sorted of verses numbers. This method was named: `findVerseClosest`. Finally, we created the method: …
=> FCBHDBP-376 ETL: add Gospel Film thumbnail info to bible_file_tags

Dockerfile, docker/run.sh, lambda/generate-dbp-etl-cfg.sh, load/Config.py, load/DBPLoadController.py, load/FilenameParser.py, load/InputFileset.py, load/InputProcessor.py, load/PreValidate.py, load/S3Utility.py, load/UpdateDBPFilesetTables.py, load/UpdateDBPTextFilesets.py, load/Validate.py, py/dbt-etl.cfg
Reverts faithcomesbyhearing/dbp-etl#71
=> Revert "add sofria-cli to generate json fileset for formatted text"

load/UpdateDBPTextFilesets.py, load/Validate.py
=> FCBHDBP-462 fix way to return log error.

load/UpdateDBPTextFilesets.py
Fix way to print error log for BiblePublisher and Sofria-cli
=> FCBHDBP fix way to print error log.

load/UpdateDBPLanguageTranslation.py
It has took off the binary code from the select queries because we have changed the collate property from the name column that belongs to language_translations entity. Also, we have updated the way to index the language name to avoid process twice the same language and so, the language name index will be set in lowercase because the name column is case insensitive. See (https://github.com/faithcomesbyhearing/dbp-etl/pull/85/files#diff-d21d9d4001c386f3021901b139bfa9036284349ef9f6a39ccb598a08c7234787R59)
I have updated the column using the following sql sentence:
```sql
ALTER TABLE language_translations MODIFY name VARCHAR(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci;
```
Also, you can check the changes if you execute the following query:
```sql
SELECT table_schema, table_name, …
```
=> FCBHDBP-369 uploader (python) - Update language_translation table with alternate language name(s)

load/UpdateDBPLanguageTranslation.py
It has improved the way to handle the language translation records with priority 5. Also, it has replaced the method update with `updateCol`.
We have changed the way to create the update statement to add information about the old value that should update. E.g.
```sql
UPDATE language_translations SET priority = '0' WHERE language_source_id='194' AND language_translation_id='6414' AND id='162891'; -- prior=9
```
@bradflood It has updated the logic to store the language translation records with EthName. if the name in AltName matches the EthName, ignore the AltName and if a language with priority 0 has the EthName value, it should change that priority to 5. The above is only with language_translation_id = 8012.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-501
- I have executed the …
=> FCBHDBP-501 Fix the way to update language translation with  priority 5

load/UpdateDBPLPTSTable.py
It has updated load/UpdateDBPLPTSTable.py class to set `admin_only` to 1 for stock_no in `bible_fileset_tags`.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-504
- I have executed the following command on my local environment to update `bible_fileset_tags` entity:
```shell
python3 load/UpdateDBPLPTSTable.py test
```
The above command returned the following outcome:
[Trans-test-lpts.sql.log](https://github.com/faithcomesbyhearing/dbp-etl/files/10192285/Trans-test-lpts.sql.log)
=> FCBHDBP-500 

load/UpdateDBPLPTSTable.py, load/Validate.py
Merge master into develop and it has removed a debug line.
=> Fcbhdbp merge dev master

load/Config.py, load/MetadataReader.py, load/MetadataReaderInterface.py, load/TestMetadataReader.py
It has created a new class named: `MetadataReader` to read USX metadata.xml file. We have created two interfaces named: 
`MetadataReaderInterface` and `MetadataRecordInterface` and we have two classes that have implemented the above interfaces.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-344
- You can run the next test unit and you should get the next output:
```shell
python3 load/TestMetadataReader.py test
```
- Output:
```shell
----------------------------------------------------------------------
Ran 8 tests in 0.071s
OK
```
=> FCBHDBP-344 Create MetadataReader to read USX metadata.xml file

load/UpdateDBPFilesetTables.py, load/UpdateDBPLPTSTable.py
This update adds support for setting the content_loaded flag for a Bible fileset when content is attached. If the XML file is loaded, the flag will be set to 0 (false) by default. If the process is executed with a path to load content, it will check whether the fileset has files to set the flag to 1 (true). Also, I attach the sql statements to alter the bible_fileset entity
```sql
-- Alter table
ALTER TABLE `bible_filesets` ADD COLUMN `content_loaded` TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE `bible_filesets` ADD COLUMN `archived` TINYINT(1) NOT NULL DEFAULT 0;
``` 
```sql
-- Set the flag content_loaded if the fileset has content loaded
UPDATE bible_filesets SET content_loaded = TRUE 
WHERE EXISTS (
SELECT bf.hash_id
FROM bible_files bf
WHERE bible_filesets.hash_id = bf.hash_id 
) OR …
```
=> Task-2116 support the new flag content_loaded.

load/LPTSExtractReader.py, load/LoadOrganizations.py, load/SQLBatchExec.py, load/SqliteUtility.py, load/UpdateDBPLPTSTable.py
update the method update_licensors according to the new logic to associate a licensor with a fileset. It has considered the fields called `LORA`, `TextAgreement` and `OtherAgreement`. Additionally,  It has considered the field: `Reg_Recording_Status`.
@bradflood , I have added the feature to create a new licensor (organization) if the licensor retrieved from XML does not exist in the DBP database.
[User Story 2172](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2172): associate license orgs for LORA
[User Story 2174](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2174): associate org licenses for "Text Only"
[User Story 2173](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2173): associate org …
=> Task 2172 associate license org

load/UpdateDBPBiblesTable.py
It has added another condition to try to determine the language ID for a specific Bible. From now on, it will try to match the language ID using values from LPTS such as: ISO, LangName, and Country.
[User Story 2175](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2175): Uploader - match on iso/langname/country
- If You run the following command and you should e.g. the warning messages
```shell
python3 load/UpdateDBPBiblesTable.py test
```
- Outcome
```shell
WARN iso: plr | name: palaka | country: cote d'ivoire did not match with StockNumber: N2PLR/GPA
WARN iso: pon | name: pohnpeian | country: micronesia, federated states of did not match with StockNumber: N2PON/UBS
WARN iso: por | name: portuguese | country: brazil did not match with StockNumber: N2POR/ACF …
```
=> Task-2175 

load/LPTSExtractReader.py, load/LoadOrganizations.py
Added the logic to handle "other" agreement plus methodology field. The rules are:
1) If more than one methodology is specified, it is ambiguous. Log it and move on.
2) For Field/Traditional Recording, the licensor is the Text Licensor
3) For virtual recordings, the licensor is the Text Licensor
4) For Partner, the licensor is the Audio Licensor and the CoLicensor is the text licensor. Log if no Co-Licensor
5) For Joint, the licensor is the Text Licensor
6) For Hear This, log (Agreement Type: Other, Methodology: Hear This. We are not able to process) and ignore
7) For OBT/Render, the licensor is the Audio Licensor (note: if no Licensor, silently ignore) 
[User Story 2176](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2176): Uploader: associate license orgs …
=> Task-2176 Uploader: associate license orgs for  "Other"

load/LPTSExtractReader.py, load/LoadOrganizations.py
It has added logic to remove the association between a licensor and a fileset when the language record attribute `Reg_Recording_Status` is Discontinued, Inactive, or Void.
[User Story 2182](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2182): uploader licensor assignment: consider RecordingStatus =  Discontinued / Inactive / Void
You should run the following command and the outcome should be the following:
```shell
python3 load/LoadOrganizations.py test
```
- Outcome
```shell
Database 'dbp_2024_03_20' is opened.
migration stage: B
migration stage: [B]
LPTS Size. Prior: 27, Current: 27
LPTS Extract with 27 records and 26 BibleIds is loaded.
num filelists 15420
ERROR ambiguous agreement and it needs to be fixed for fileset id: …
```
=> Task-2182 uploader licensor assignment: consider RecordingStatus =  Discontinued / Inactive / Void

load/LPTSExtractReader.py, load/LanguageReader.py, load/LoadOrganizations.py, load/PreValidate.py, load/TestLanguageReaderStage.py, load/UpdateDBPAccessTable.py
Added logic to split the licensor and co-licensor values by semicolon and then insert multiple licensors and co-licensors for each fileset record
[User Story 2184](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2184): blimp - licensor association: split licensor and colicensor by semicolon before processing
To run the test and get the expected result with entry 25: `Entry 25: N2MUP/NLL, two licensors in the same field, need to be split`, I have updated the `lpts-dbp.xml` and the attribute `Licensor` for the stock number `N2MUP/NLL`. I have added the separator `;` to get the split values. For example:
```xml
<Licensor>Malvoday ; New Life Literature</Licensor>
```
You should run the following command and the outcome should be the following:
```shell
python3 …
```
=> Task 2184 licensor association: split licensor and colicensor by semicolon before processing

load/UpdateDBPBiblesTable.py
Added logic to allow removing the Bible records when all filesets that belong to the Bible are not loaded.
[User Story 2185](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2185): uploader: allow deletion of bible and fileset when all filesets are not loaded
You should run the following command and the outcome should be the following:
```shell
python3 load/UpdateDBPBiblesTable.py test
```
- Outcome
[log_remove_bibles.txt](https://github.com/faithcomesbyhearing/dbp-etl/files/15396155/log_remove_bibles.txt)
=> Task-2185 allow deletion of bible and fileset when all filesets are not loaded

load/LoadOrganizations.py, load/SQLBatchExec.py
The SQLBatchExec class has been updated to use INSERT instead of INSERT IGNORE. Additionally, we have improved the logic to create an organization and organization translation to cover the case when we find an organization by slug but the organization translation does not exist. Therefore, we need to create the organization translation.
[Bug 2191](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2191): uploader: organization creation failure
I have modified the lpts-dbp.xml to add the licensor `Mision Alemana entre los Nativos del Paraguay` into the language record N2MUP/NLL to recreate the case where it has to create the new organization translation:
- lpts-dbp.xml
```xml
<Licensor>Malvoday ; New Life Literature; Mision Alemana entre los Nativos del …
```
=> Task-2191 uploader: organization creation failure

load/FilenameParser.py
=> Merge from master to Dev

Dockerfile, docker/run.sh, load/BlimpLanguageRecord.py, load/Config.py, load/DBPLoadController.py, load/InputFileset.py, load/MondayBoard.py, load/MondayHTTP.py, load/MondayProductCodeBoard.py, load/S3Utility.py, load/S3ZipperService.py, load/UpdateDBPBibleFilesSecondary.py, load/UpdateDBPBooksTable.py, load/UpdateDBPFilesetTables.py, load/UpdateDBPLPTSTable.py
Based on the Gospel Film videos, this commit implements the following features: 
- Creating a zip file using s3zipper.
- Uploading a zip by book ID
-  Updating the Monday Product Code board with the CDN link that points to the new zip file.
[User Story 2614](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2614): uploader: create and publish zip for Gospel Films
We need to create the following new config parameters:
- s3.aws_region
- s3.zipper.user_key
- s3.zipper.user_secret
- cdn.partner_base
- monday.completed_product_code.api_key
- monday.completed_product_code.board_id
- The s3zipper will use the config.s3_aws_profile value to create AWS temporary credentials, so this profile must have permissions to read and write to the dbp-vid bucket.
- It will update …
=> Task-2614 uploader: create and publish zip for Gospel Films

load/UpdateDBPFilesetTables.py
Added a feature that assigns a chapter and verse one greater than the current maximum for each book when calculating the chapter for end_credits files. E.g.
````shell
Book ID 	MaxChapter	ChapterEndCredits
ACT			28			29
MAT			28			29
MRK			16			17
LUK			24			25
JHN			21			22
`````
[User Story 2467](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2467): (R)Enable loading of Acts films
I have used to filesets to test it: FANBSGP2DV (Acts Films) and FANBSGP2DV (Gospel Films)
``````shell
time python3 load/DBPLoadController.py test s3://etl-development-input/ "FANBSGP2DV"
INSERT  INTO bible_files (chapter_end, verse_end, file_name, file_size, duration, verse_sequence, hash_id, book_id, chapter_start, verse_start) VALUES ('29', '1', …
=> Task-2647 Hotfix: (R)Enable loading of Acts films

load/MondayProductCodeBoard.py
Update the label related to the Stocknumber column of the Monday CPC Board.
=> Monday - Update the label related to the Stocknumber column

load/BibleBrainService.py, load/Config.py, load/InputFileset.py, load/S3ZipperService.py, load/UpdateDBPBibleFilesSecondary.py
Implement PDF fetching from BibleBrain service.
- Implemented service for fetching PDFs from BibleBrain API
- Added retry logic for handling transient errors
- Integrated S3 upload functionality for retrieved PDFs
- Added automatic PDF inclusion in ZIP packages
- Exclude the PDFs from the parsing validation
[User Story 2800](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2800): include copyright pdf in zip files created by uploader
- You can use the new service with the following command:
``````shell
-> time python3 load/BibleBrainService.py test
Config:setConfigParametersFromProfile. profile: test, programRunning: BibleBrainService.py
AWSSession...assume role arn is not provided. If this is not a docker execution, check dbp-etl.cfg …
=> Task-2800 include copyright pdf in zip files created by uploader

load/DBPLoadController.py
Change the content loading logic, specifically, the processing order. From now on, all database changes will be processed before calling the biblebrain-services API to create the ZIP and copyright PDF. This ensures that the product code references are created before they are used to generate the copyright PDF for each fileset.
[Bug 2844](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2844): Uploader: Use product code to generate the copyright PDF
I have tested using the following two command and I have validated that the zip file contains the copyright pdf:
- Audio Content
``````shell
time python3 load/DBPLoadController.py test s3://etl-development-input/ "ENGESVN2DA"
```````
You need to ensure that the product_code is created:
`````sql
INSERT INTO …
```
=> Task-2844 Uploader: Use product code to generate the copyright PDF
